### ISSUE TITLE
cps function pointers / indirect function calls

### ISSUE THREAD

**Issue by zevv** [nim-works/cps#183]
This would be nice to have

```nim
import cps
     
type                               
  C = ref object of Continuation    
  callback = proc(n: int) {.cps:C.}
    
proc foo(n: int) {.cps:C.} =
  echo "foo ", n
  
proc bar(fn: callback) {.cps:C.} =
  echo "bar1"
  fn(42) 
  echo "bar2"
  
var c = whelp bar(foo)
discard c.trampoline
```

but

```
/home/ico/sandbox/prjs/cps/cps.nim(71, 21) cps
/home/ico/sandbox/prjs/cps/cps/transform.nim(889, 28) cpsTransformProc
/home/ico/sandbox/prjs/cps/cps/normalizedast.nim(46, 13) normalizeProcDef
/home/ico/external/Nim/lib/core/macros.nim(638, 24) expectKind
/tmp/t.nim(7, 14) Error: Expected a node of kind nnkProcDef, got nnkProcTy
```

**Comment by alaviss** [comment]
I think we can invent a calling convention for CPS. Basically an object like

```nim
type
  Whelp[C: Continuation; R; Fn: proc] = object
    fn: C # the `whelp` function
    rs: proc (cont: C): R # a function that take the continuation and emit its result
```

Then we can turn:

```nim
type callback = proc() {.cps:C.}
```

into

```nim
type callback = Whelp[C, void, proc(): C]
```

Then we implement a macro to turn `foo` -> a `Whelp` object.

This should give us enough data within CPS to perform the call.

**Comment by Riderfighter** [comment]
This is a feature that I am looking forward to having. Currently in my project I would like to make the use of a function lookup table but this hinders my lookup abilities.

**Comment by zevv** [comment]
Some more fiddling with closures and magic got me to the point where I can actually pass control to a new spawned continuation; the only missing step here is getting the result:

```
import cps
import sugar
                     
type
  C = ref object of Continuation 
    thing: int

  Callback = proc(n: int): C     
                         
proc pass*(cFrom, cTo: C): C =
  echo "pass"
  cTo.thing = cFrom.thing
  cTo

proc checkThing(c: C) {.cpsVoodoo.} =
  assert c.thing == 11

proc run(c: C, c2: C): C {.cpsMagic.} =
  c2.mom = c
  c2.thing = c.thing
  c2

proc bar(gen: Callback) {.cps:C.} =
  run gen(42) 
  var r = 0      # now what?
  echo "r=", r

proc timesTwo(n: int): int {.cps:C.} =
  checkThing()
  result = n * 2

let c = whelp bar((n) => whelp timesTwo(n))
c.thing = 11
discard c.trampoline()
```

What do I do at the `now what` line?  After ignoring disruptek for a hundred times when he was talking about getting the result from a cont, I finally need it. Yeah yeah.

**Comment by zevv** [comment]
For those interested, I'm using this in a limited way in cpstest now to dispatch HTTP server paths:

https://github.com/zevv/cpstest/blob/master/main.nim#L70

Still a bit clumsy, right

**Comment by disruptek** [comment]
We'll try the calling convention idea.  And we'll try not to make it too magical right off the bat.  I'll make implementing this a priority if @alaviss doesn't bang it out first.

**Comment by zevv** [comment]
Hooray, progress on the notorious #183, congrats!

I've been able to make something work using the `cc` branch, although the interface is more then horrible at this time. Sure we can figure that out.

My minimal example, pretty, pretty much similar as from the tests:

```

import cps

type C = Continuation

proc addone(val: int): int {.cps:C.} =
  echo "addone ", val
  return val + 1


proc addtwo(val: int): int {.cps:C.} =
  echo "addtwo ", val
  return val + 2

const thing = whelp addone
type Callback = typeOf thing


proc foo(val: int, cb: Callback) {.cps:C.} =
  let a = cb.call(val)         
  echo "a = ", cb.result(a)


let cb = whelp addtwo

var f: C = whelp foo(1, cb)
f = trampoline f
```

Things we need to discuss:

- how do we call this? A callback? a callable? A cps function pointer?
- type of the thing: Can we formalize a type or create a macro to generate a type for a callback? `type Callback = typeOf thing` is funny as hell, but not really usable.
- cps-cps calling convention. Is there anything against making this look like ye olde regular cpscps function call? So let's see if we can replace the `let a = cb.call(val); echo "a = ", cb.result(a)` with `echo "a = ", cv(val)`

**Comment by disruptek** [comment]
I updated your example to use the `.cps.` typedef macro to define the type.

We're working on the syntax and might be able to do away with `call`.
