### ISSUE TITLE
prefix leg names with original proc name

### ISSUE THREAD

**Issue by zevv** [nim-works/cps#198]
That would make `trace()` output much more readable.

**Comment by disruptek** [comment]
I don't have any great ideas on how to do this _trivially_ without cheating with a global or something, but here's what I came up with:

We get more strict about using `newAnnotation`, and we have it pass the original cps procedure's identifier and maybe a bunch of other interesting data.  Then we use `debugAnnotation` to also shadow `makeContProc` with a closure that first mutates the name argument.  To that end, I rewrote `cpsTryExcept` in bf9f4766d8ee946fbca9d3d48149c32b7b4cd241 to also use `debugAnnotation`.  I think that's the only outstanding case that both calls `makeContProc` and was lacking the `debugAnnotation` syntax.

**Comment by disruptek** [comment]
This is also a #190 problem.
