### ISSUE TITLE
CallNodes = nnkCallKinds

### ISSUE THREAD

**Issue by Gruruya** [nim-works/cps#293]
https://github.com/nim-works/cps/blob/5645eb5838e6d30d484fbe23d8c590201e520630/cps/transform.nim#L9-L10

https://github.com/nim-lang/Nim/pull/21833
https://github.com/nim-lang/Nim/pull/21829

**Comment by disruptek** [comment]
Do you feel like creating a PR?

**Comment by Gruruya** [comment]
Should I remove all of the `nnkHiddenCallConv` stuff or make a new type to emulate what it was?

**Comment by Gruruya** [comment]
I have no clue what a `nnkHiddenCallConv` is or why it matters but you're probably right. I'll stare at the code some more.

**Comment by disruptek** [comment]
Basically, we only want to rewrite certain kinds of calls in certain circumstances...

**Comment by Gruruya** [comment]
Right, I got that. I don't understand why the set would be changed without the behavior changing, but you do seem to know, so don't let me waste too much of your time.

**Comment by Gruruya** [comment]
Yeah it does, I meant to imply your second option.
