### ISSUE TITLE
Error: unhandled exception: invalid object conversion [ObjectConversionDefect]

### ISSUE THREAD

**Issue by blackmius** [nim-works/cps#321]
I am trying to delay continuation until data is available so I push continuation to some queue there it live until data is available then I trampoline to it again. for this I created specific Continuation type which storing data result in self.

the minimal example to recreate the error

```nim
import pkg/cps

type C = ref object of Continuation
  data: int

var conts = newSeq[C]()

proc jield(c: C): C {.cpsMagic.} =
  conts.add(c)

proc B() {.cps: C.} =
  jield()

proc A() {.cps: Continuation.} =
  B()

A()
discard trampoline conts[0]
```

error traceback

```
/home/user/projects/uasync/experiments/a.nim(18) a
/home/user/projects/Nim/lib/system.nim(919) trampoline
/home/user/projects/Nim/lib/system/fatal.nim(53) sysFatal
Error: unhandled exception: invalid object conversion [ObjectConversionDefect]
```

but if I use C from every start, in code above changing A to also use Continuation C everything works

```nim
proc A() {.cps: C.} =
  B()
```

**Comment by blackmius** [comment]
also changing 
``` nim
var conts = newSeq[C]()
```
to
``` nim
var conts = newSeq[Continuation]()
```
work

**Comment by alaviss** [comment]
A workaround is to convert your continuation to `Continuation` before trampolining it:

```nim
discard trampoline Continuation(conts[0])
```

This issue happens because your `C` eventually transition back to `Continuation` but `trampoline[C]` assumes that you start with `C` and ends with `C`.

I'm not sure what should be the correct behavior here, though. Maybe we should provide a version of `trampoline` that ends with `Continuation`.

**Comment by disruptek** [comment]
I don't think there's a better design than taking T and returning T, but the `bounce()` is subtle enough that it should probably be provided by cps.

**Comment by disruptek** [comment]
Closing because this behavior seems to be correct.
